name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'   # REQUIRED for Workload Identity Federation

    steps:
      - uses: actions/checkout@v4

      # Authenticate using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/850618567800/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer@scribble-hub-45904.iam.gserviceaccount.com'

      # Deploy to Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # auto-created by GitHub
          channelId: live
          projectId: scribble-hub-45904
